Repository locationtech/rasterframes, pull requests merged in 2020-02, with the labels that each got.

#468 Fix #467: missing geotrellis-s3-spark dependency
  build.sbt
Labels: build

#460 Add rf_sqrt square root
  core/src/main/scala/org/locationtech/rasterframes/expressions/localops/Exp.scala
  core/src/main/scala/org/locationtech/rasterframes/expressions/localops/Sqrt.scala
  core/src/main/scala/org/locationtech/rasterframes/expressions/package.scala
  core/src/main/scala/org/locationtech/rasterframes/functions/LocalFunctions.scala
  core/src/test/scala/org/locationtech/rasterframes/functions/LocalFunctionsSpec.scala
  docs/src/main/paradox/reference.md
  docs/src/main/paradox/release-notes.md
  pyrasterframes/src/main/python/pyrasterframes/rasterfunctions.py
  pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
Labels: enhancement

#478 Pin jupyter-client version for comatibility with pweave
  .circleci/config.yml
  pyrasterframes/src/main/python/requirements.txt
  pyrasterframes/src/main/python/setup.py
  pyrasterframes/src/main/python/tests/GeotrellisTests.py
Labels: build, maintenance
